CREATE DATABASE IF NOT EXISTS spa;
USE spa;
CREATE TABLE IF NOT EXISTS chats(
	id INT AUTO_INCREMENT,
    nom VARCHAR(40),
    age TINYINT,
    couleur_id TINYINT,
    CONSTRAINT pk_chats PRIMARY KEY(id)
)ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS couleur(
	id INT AUTO_INCREMENT,
    nom VARCHAR(60),
    CONSTRAINT pk_couleur PRIMARY KEY(id)
)ENGINE=InnoDB;


